sudo: required
services:
  - docker

before_install:
  - docker build -t kaprisa/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run kaprisa/react-test npm test -- --coverage

after_success:
  - docker build -t kaprisa/multi-client ./client
  - docker build -t kaprisa/multi-nginx ./nginx
  - docker build -t kaprisa/multi-api ./server
  - docker build -t kaprisa/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push kaprisa/multi-client
  - docker push kaprisa/multi-nginx
  - docker push kaprisa/multi-api
  - docker push kaprisa/multi-worker


